/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Recorder {
  constructor(deviceIndex?: number | undefined | null)
  /**
   * Start capturing audio. The callback is invoked on a dedicated drain
   * thread each time new samples are available from the microphone.
   */
  start(callback: (err: Error | null, samples: Int16Array) => void): void
  stop(): void
  get sampleRate(): number
  static getAudioDevices(): Array<AudioDevice>
}

/**
 * Exposed to JavaScript as a plain object.
 * `index` is `i32` because JavaScript has no unsigned integer type.
 * The value is always non-negative.
 */
export interface AudioDevice {
  index: number
  name: string
}
